title: Music, technology and arts curiosities
author: Fer Molochnik
email: fernandolopezmolochnik@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Music song writing technologies

# social links
# twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  fmolochnik

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
